export const FETCH_PAYLIST = 'FETCH_PAYLIST';
export const SUBMIT_PAY = 'SUBMIT_PAY';
export const FETCH_PAYLISTLOADING = 'FETCH_PAYLISTLOADING';
export const FETCH_AMOUNTLIST = 'FETCH_AMOUNTLIST'; 
export const FETCH_AMOUNTDEFAULT = 'FETCH_AMOUNTDEFAULT';
export const FETCH_PAYMENTFLAG = 'FETCH_PAYMENTFLAG'; 